### ISSUE TITLE
Citing?

### ISSUE THREAD

**Issue by mlubin** [lgottwald/PaPILO#49]
I'd like to cite PaPILO in a publication. What's the preferred document to cite? The GitHub page, or perhaps the SCIP 7 report?

**Comment by ambros-gleixner** [comment]
Hi Miles! We are working on a preprint, but currently the SCIP 7 report is still the best paper to cite.

A new official repo will go online soon (maybe today) at github.com/scipopt/papilo. This link would be the best to mention as the location of the source code.

**Comment by mlubin** [comment]
Great, thanks! Looking forward to the preprint.
