### ISSUE TITLE
Configuring incomplete, errors occurred!

### ISSUE THREAD

**Issue by zrjer** [lgottwald/PaPILO#53]
Hello,
I get an error when I use CMake to build PaPILO 
“
CMake Error at cmake/Modules/FindTBB.cmake:50 (set_target_properties):
  set_target_properties called with incorrect number of arguments.
Call Stack (most recent call first):
  CMakeLists.txt:96 (find_package)
”
How can I solve this situation?
Thanks!

**Comment by alexhoen** [comment]
as stated in the README the repro is outdated. Please use the repro that is linked in the repro and submit the the log output please if the error still occurs.
