### ISSUE TITLE
Fix condition to link to libatomic

### ISSUE THREAD

**Issue by barracuda156** [lgottwald/PaPILO#55]
CMakeLists has the following currently:
```
# on raspberry pi, we need to link libatomic, as libtbbmalloc_proxy depends on it
if((CMAKE_HOST_SYSTEM_PROCESSOR STREQUAL "armv7l") AND (CMAKE_SYSTEM_NAME STREQUAL "Linux"))
    target_link_libraries(papilo INTERFACE atomic)
endif()
```
In fact, this has nothing to do with raspberry pi or Linux, but only with the arch and compiler. GCC needs `libatomic` on a number of 32-bit archs, which include arm, ppc and mips.

So, for example, PaPILO fails to build on macOS on `ppc` due to missing `___atomic_fetch_add_8`, unless `-latomic` is passed manually.

The right way would be to check if 64-bit atomics is supported without `libatomic`, and link it if the check fails.

**Comment by alexhoen** [comment]
note that this repo is outdated as stated in README. please go to https://github.com/scipopt/papilo
